import {
  createAsyncThunk,
  createSlice,
  createSelector,
} from "@reduxjs/toolkit";

export const countries = [
  {
    id: 1,
    name: "Afghanistan",
    country_code: "AF",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/af.svg",
    phone_code: "+93",
    country_code3: "AFG",
    continent_id: 3,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 2,
    name: "Albania",
    country_code: "AL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/al.svg",
    phone_code: "+355",
    country_code3: "ALB",
    continent_id: 4,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 3,
    name: "Algeria",
    country_code: "DZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/dz.svg",
    phone_code: "+213",
    country_code3: "DZA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 4,
    name: "Andorra",
    country_code: "AD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ad.svg",
    phone_code: "+376",
    country_code3: "AND",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 5,
    name: "Angola",
    country_code: "AO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ao.svg",
    phone_code: "+244",
    country_code3: "AGO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 6,
    name: "Antigua and Barbuda",
    country_code: "AG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ag.svg",
    phone_code: "+1-268",
    country_code3: "ATG",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 7,
    name: "Argentina",
    country_code: "AR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ar.svg",
    phone_code: "+54",
    country_code3: "ARG",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 8,
    name: "Armenia",
    country_code: "AM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/am.svg",
    phone_code: "+374",
    country_code3: "ARM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 9,
    name: "Australia",
    country_code: "AU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/au.svg",
    phone_code: "+61",
    country_code3: "AUS",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 10,
    name: "Austria",
    country_code: "AT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/at.svg",
    phone_code: "+43",
    country_code3: "AUT",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 11,
    name: "Azerbaijan",
    country_code: "AZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/az.svg",
    phone_code: "+994",
    country_code3: "AZE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 12,
    name: "Bahamas",
    country_code: "BS",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bs.svg",
    phone_code: "+1-242",
    country_code3: "BHS",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 13,
    name: "Bahrain",
    country_code: "BH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bh.svg",
    phone_code: "+973",
    country_code3: "BHR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 14,
    name: "Bangladesh",
    country_code: "BD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bd.svg",
    phone_code: "+880",
    country_code3: "BGD",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 15,
    name: "Barbados",
    country_code: "BB",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bb.svg",
    phone_code: "+1-246",
    country_code3: "BRB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 16,
    name: "Belarus",
    country_code: "BY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/by.svg",
    phone_code: "+375",
    country_code3: "BLR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 17,
    name: "Belgium",
    country_code: "BE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/be.svg",
    phone_code: "+32",
    country_code3: "BEL",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 18,
    name: "Belize",
    country_code: "BZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bz.svg",
    phone_code: "+501",
    country_code3: "BLZ",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 19,
    name: "Benin",
    country_code: "BJ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bj.svg",
    phone_code: "+229",
    country_code3: "BEN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 20,
    name: "Bhutan",
    country_code: "BT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bt.svg",
    phone_code: "+975",
    country_code3: "BTN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 21,
    name: "Bolivia",
    country_code: "BO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bo.svg",
    phone_code: "+591",
    country_code3: "BOL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 22,
    name: "Bosnia and Herzegovina",
    country_code: "BA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ba.svg",
    phone_code: "+387",
    country_code3: "BIH",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 23,
    name: "Botswana",
    country_code: "BW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bw.svg",
    phone_code: "+267",
    country_code3: "BWA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 24,
    name: "Brazil",
    country_code: "BR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/br.svg",
    phone_code: "+55",
    country_code3: "BRA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 25,
    name: "Brunei",
    country_code: "BN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bn.svg",
    phone_code: "+673",
    country_code3: "BRN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 26,
    name: "Bulgaria",
    country_code: "BG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bg.svg",
    phone_code: "+359",
    country_code3: "BGR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 27,
    name: "Burkina Faso",
    country_code: "BF",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bf.svg",
    phone_code: "+226",
    country_code3: "BFA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 28,
    name: "Burundi",
    country_code: "BI",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/bi.svg",
    phone_code: "+257",
    country_code3: "BDI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 29,
    name: "Cabo Verde",
    country_code: "CV",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cv.svg",
    phone_code: "+238",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 30,
    name: "Cambodia",
    country_code: "KH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/kh.svg",
    phone_code: "+855",
    country_code3: "KHM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 31,
    name: "Cameroon",
    country_code: "CM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cm.svg",
    phone_code: "+237",
    country_code3: "CMR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 32,
    name: "Canada",
    country_code: "CA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ca.svg",
    phone_code: "+1",
    country_code3: "CAN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 33,
    name: "Central African Republic",
    country_code: "CF",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cf.svg",
    phone_code: "+236",
    country_code3: "CAF",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 34,
    name: "Chad",
    country_code: "TD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/td.svg",
    phone_code: "+235",
    country_code3: "TCD",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 35,
    name: "Chile",
    country_code: "CL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cl.svg",
    phone_code: "+56",
    country_code3: "CHL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 36,
    name: "China",
    country_code: "CN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cn.svg",
    phone_code: "+86",
    country_code3: "CHN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 37,
    name: "Colombia",
    country_code: "CO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/co.svg",
    phone_code: "+57",
    country_code3: "COL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 38,
    name: "Comoros",
    country_code: "KM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/km.svg",
    phone_code: "+269",
    country_code3: "COM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 39,
    name: "Congo",
    country_code: "CG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+242",
    country_code3: "COG",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 40,
    name: "Congo (Democratic Republic)",
    country_code: "CD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cd.svg",
    phone_code: "+243",
    country_code3: "COD",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 41,
    name: "Costa Rica",
    country_code: "CR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cr.svg",
    phone_code: "+506",
    country_code3: "CRI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 42,
    name: "Croatia",
    country_code: "HR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/hr.svg",
    phone_code: "+385",
    country_code3: "HRV",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 43,
    name: "Cuba",
    country_code: "CU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cu.svg",
    phone_code: "+53",
    country_code3: "CUB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 44,
    name: "Cyprus",
    country_code: "CY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cy.svg",
    phone_code: "+357",
    country_code3: "CYP",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 45,
    name: "Czech Republic",
    country_code: "CZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/cz.svg",
    phone_code: "+420",
    country_code3: "CZE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 46,
    name: "Denmark",
    country_code: "DK",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/dk.svg",
    phone_code: "+45",
    country_code3: "DNK",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 47,
    name: "Djibouti",
    country_code: "DJ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/dj.svg",
    phone_code: "+253",
    country_code3: "DJI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 48,
    name: "Dominica",
    country_code: "DM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/dm.svg",
    phone_code: "+1-767",
    country_code3: "DMA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 49,
    name: "Dominican Republic",
    country_code: "DO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/do.svg",
    phone_code: "+1-809",
    country_code3: "DOM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 50,
    name: "East Timor",
    country_code: "TL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+670",
    country_code3: "TLS",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 51,
    name: "Ecuador",
    country_code: "EC",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ec.svg",
    phone_code: "+593",
    country_code3: "ECU",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 52,
    name: "Egypt",
    country_code: "EG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/eg.svg",
    phone_code: "+20",
    country_code3: "EGY",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 53,
    name: "El Salvador",
    country_code: "SV",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sv.svg",
    phone_code: "+503",
    country_code3: "SLV",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 54,
    name: "Equatorial Guinea",
    country_code: "GQ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gq.svg",
    phone_code: "+240",
    country_code3: "GNQ",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 55,
    name: "Eritrea",
    country_code: "ER",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/er.svg",
    phone_code: "+291",
    country_code3: "ERI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 56,
    name: "Estonia",
    country_code: "EE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ee.svg",
    phone_code: "+372",
    country_code3: "EST",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 57,
    name: "Eswatini",
    country_code: "SZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sz.svg",
    phone_code: "+268",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 58,
    name: "Ethiopia",
    country_code: "ET",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/et.svg",
    phone_code: "+251",
    country_code3: "ETH",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 59,
    name: "Fiji",
    country_code: "FJ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/fj.svg",
    phone_code: "+679",
    country_code3: "FJI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 60,
    name: "Finland",
    country_code: "FI",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/fi.svg",
    phone_code: "+358",
    country_code3: "FIN",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 61,
    name: "France",
    country_code: "FR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/fr.svg",
    phone_code: "+33",
    country_code3: "FRA",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 62,
    name: "Gabon",
    country_code: "GA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ga.svg",
    phone_code: "+241",
    country_code3: "GAB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 63,
    name: "Gambia",
    country_code: "GM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gm.svg",
    phone_code: "+220",
    country_code3: "GMD",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 64,
    name: "Georgia",
    country_code: "GE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ge.svg",
    phone_code: "+995",
    country_code3: "GEO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 65,
    name: "Germany",
    country_code: "DE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/de.svg",
    phone_code: "+49",
    country_code3: "DEU",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 66,
    name: "Ghana",
    country_code: "GH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gh.svg",
    phone_code: "+233",
    country_code3: "GHA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 67,
    name: "Greece",
    country_code: "GR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gr.svg",
    phone_code: "+30",
    country_code3: "GRC",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 68,
    name: "Grenada",
    country_code: "GD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gd.svg",
    phone_code: "+1-473",
    country_code3: "GRD",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 69,
    name: "Guatemala",
    country_code: "GT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gt.svg",
    phone_code: "+502",
    country_code3: "GTM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 70,
    name: "Guinea",
    country_code: "GN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gn.svg",
    phone_code: "+224",
    country_code3: "GIN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 71,
    name: "Guinea-Bissau",
    country_code: "GW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gw.svg",
    phone_code: "+245",
    country_code3: "GNB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 72,
    name: "Guyana",
    country_code: "GY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gy.svg",
    phone_code: "+592",
    country_code3: "GUY",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 73,
    name: "Haiti",
    country_code: "HT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ht.svg",
    phone_code: "+509",
    country_code3: "HTI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 74,
    name: "Honduras",
    country_code: "HN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/hn.svg",
    phone_code: "+504",
    country_code3: "HND",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 75,
    name: "Hungary",
    country_code: "HU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/hu.svg",
    phone_code: "+36",
    country_code3: "HUN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 76,
    name: "Iceland",
    country_code: "IS",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/is.svg",
    phone_code: "+354",
    country_code3: "ISL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 77,
    name: "India",
    country_code: "IN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/in.svg",
    phone_code: "+91",
    country_code3: "IND",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 78,
    name: "Indonesia",
    country_code: "ID",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/id.svg",
    phone_code: "+62",
    country_code3: "IDN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 79,
    name: "Iran",
    country_code: "IR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ir.svg",
    phone_code: "+98",
    country_code3: "IRN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 80,
    name: "Iraq",
    country_code: "IQ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/iq.svg",
    phone_code: "+964",
    country_code3: "IRQ",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 81,
    name: "Ireland",
    country_code: "IE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ie.svg",
    phone_code: "+353",
    country_code3: "IRL",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 82,
    name: "Israel",
    country_code: "IL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/il.svg",
    phone_code: "+972",
    country_code3: "ISR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 83,
    name: "Italy",
    country_code: "IT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/it.svg",
    phone_code: "+39",
    country_code3: "ITA",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 84,
    name: "Jamaica",
    country_code: "JM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/jm.svg",
    phone_code: "+1-876",
    country_code3: "JAM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 85,
    name: "Japan",
    country_code: "JP",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/jp.svg",
    phone_code: "+81",
    country_code3: "JPN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 86,
    name: "Jordan",
    country_code: "JO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/jo.svg",
    phone_code: "+962",
    country_code3: "JOR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 87,
    name: "Kazakhstan",
    country_code: "KZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/kz.svg",
    phone_code: "+7",
    country_code3: "KAZ",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 88,
    name: "Kenya",
    country_code: "KE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ke.svg",
    phone_code: "+254",
    country_code3: "KEN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 89,
    name: "Kiribati",
    country_code: "KI",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ki.svg",
    phone_code: "+686",
    country_code3: "KIR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 90,
    name: "Korea (North)",
    country_code: "KP",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+850",
    country_code3: "PRK",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 91,
    name: "Korea (South)",
    country_code: "KR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+82",
    country_code3: "KOR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 92,
    name: "Kuwait",
    country_code: "KW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/kw.svg",
    phone_code: "+965",
    country_code3: "KWT",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 93,
    name: "Kyrgyzstan",
    country_code: "KG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/kg.svg",
    phone_code: "+996",
    country_code3: "KGZ",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 94,
    name: "Laos",
    country_code: "LA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/la.svg",
    phone_code: "+856",
    country_code3: "LAO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 95,
    name: "Latvia",
    country_code: "LV",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lv.svg",
    phone_code: "+371",
    country_code3: "LVA",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 96,
    name: "Lebanon",
    country_code: "LB",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lb.svg",
    phone_code: "+961",
    country_code3: "LBN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 97,
    name: "Lesotho",
    country_code: "LS",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ls.svg",
    phone_code: "+266",
    country_code3: "LSO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 98,
    name: "Liberia",
    country_code: "LR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lr.svg",
    phone_code: "+231",
    country_code3: "LBR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 99,
    name: "Libya",
    country_code: "LY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ly.svg",
    phone_code: "+218",
    country_code3: "LBY",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 100,
    name: "Liechtenstein",
    country_code: "LI",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/li.svg",
    phone_code: "+423",
    country_code3: "LIE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 101,
    name: "Lithuania",
    country_code: "LT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lt.svg",
    phone_code: "+370",
    country_code3: "LTU",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 102,
    name: "Luxembourg",
    country_code: "LU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lu.svg",
    phone_code: "+352",
    country_code3: "LUX",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 103,
    name: "Madagascar",
    country_code: "MG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mg.svg",
    phone_code: "+261",
    country_code3: "MDG",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 104,
    name: "Malawi",
    country_code: "MW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mw.svg",
    phone_code: "+265",
    country_code3: "MWI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 105,
    name: "Malaysia",
    country_code: "MY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/my.svg",
    phone_code: "+60",
    country_code3: "MYS",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 106,
    name: "Maldives",
    country_code: "MV",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mv.svg",
    phone_code: "+960",
    country_code3: "MDV",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 107,
    name: "Mali",
    country_code: "ML",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ml.svg",
    phone_code: "+223",
    country_code3: "MLI",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 108,
    name: "Malta",
    country_code: "MT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mt.svg",
    phone_code: "+356",
    country_code3: "MLT",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 109,
    name: "Marshall Islands",
    country_code: "MH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mh.svg",
    phone_code: "+692",
    country_code3: "MHL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 110,
    name: "Mauritania",
    country_code: "MR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mr.svg",
    phone_code: "+222",
    country_code3: "MRT",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 111,
    name: "Mauritius",
    country_code: "MU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mu.svg",
    phone_code: "+230",
    country_code3: "MUS",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 112,
    name: "Mexico",
    country_code: "MX",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mx.svg",
    phone_code: "+52",
    country_code3: "MEX",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 113,
    name: "Micronesia",
    country_code: "FM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+691",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 114,
    name: "Moldova",
    country_code: "MD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/md.svg",
    phone_code: "+373",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 115,
    name: "Monaco",
    country_code: "MC",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mc.svg",
    phone_code: "+377",
    country_code3: "MCO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 116,
    name: "Mongolia",
    country_code: "MN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mn.svg",
    phone_code: "+976",
    country_code3: "MNG",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 117,
    name: "Montenegro",
    country_code: "ME",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/me.svg",
    phone_code: "+382",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 118,
    name: "Morocco",
    country_code: "MA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ma.svg",
    phone_code: "+212",
    country_code3: "MAR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 119,
    name: "Mozambique",
    country_code: "MZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mz.svg",
    phone_code: "+258",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 120,
    name: "Myanmar",
    country_code: "MM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mm.svg",
    phone_code: "+95",
    country_code3: "MMR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 121,
    name: "Namibia",
    country_code: "NA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/na.svg",
    phone_code: "+264",
    country_code3: "NAM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 122,
    name: "Nauru",
    country_code: "NR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/nr.svg",
    phone_code: "+674",
    country_code3: "NRU",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 123,
    name: "Nepal",
    country_code: "NP",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/np.svg",
    phone_code: "+977",
    country_code3: "NPL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 124,
    name: "Netherlands",
    country_code: "NL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/nl.svg",
    phone_code: "+31",
    country_code3: "NLD",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 125,
    name: "New Zealand",
    country_code: "NZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/nz.svg",
    phone_code: "+64",
    country_code3: "NZL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 126,
    name: "Nicaragua",
    country_code: "NI",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ni.svg",
    phone_code: "+505",
    country_code3: "NIC",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 127,
    name: "Niger",
    country_code: "NE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ne.svg",
    phone_code: "+227",
    country_code3: "NER",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 128,
    name: "Nigeria",
    country_code: "NG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ng.svg",
    phone_code: "+234",
    country_code3: "NGA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 129,
    name: "North Macedonia",
    country_code: "MK",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/mk.svg",
    phone_code: "+389",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 130,
    name: "Norway",
    country_code: "NO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/no.svg",
    phone_code: "+47",
    country_code3: "NOR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 131,
    name: "Oman",
    country_code: "OM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/om.svg",
    phone_code: "+968",
    country_code3: "OMN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 132,
    name: "Pakistan",
    country_code: "PK",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pk.svg",
    phone_code: "+92",
    country_code3: "PAK",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 133,
    name: "Palau",
    country_code: "PW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pw.svg",
    phone_code: "+680",
    country_code3: "PLW",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 134,
    name: "Panama",
    country_code: "PA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pa.svg",
    phone_code: "+507",
    country_code3: "PAN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 135,
    name: "Papua New Guinea",
    country_code: "PG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pg.svg",
    phone_code: "+675",
    country_code3: "PNG",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 136,
    name: "Paraguay",
    country_code: "PY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/py.svg",
    phone_code: "+595",
    country_code3: "PRY",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 137,
    name: "Peru",
    country_code: "PE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pe.svg",
    phone_code: "+51",
    country_code3: "PER",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 138,
    name: "Philippines",
    country_code: "PH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ph.svg",
    phone_code: "+63",
    country_code3: "PHL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 139,
    name: "Poland",
    country_code: "PL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pl.svg",
    phone_code: "+48",
    country_code3: "POL",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 140,
    name: "Portugal",
    country_code: "PT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/pt.svg",
    phone_code: "+351",
    country_code3: "PRT",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 141,
    name: "Qatar",
    country_code: "QA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/qa.svg",
    phone_code: "+974",
    country_code3: "QAT",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 142,
    name: "Romania",
    country_code: "RO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ro.svg",
    phone_code: "+40",
    country_code3: "ROU",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 143,
    name: "Russia",
    country_code: "RU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ru.svg",
    phone_code: "+7",
    country_code3: "RUS",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 144,
    name: "Rwanda",
    country_code: "RW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/rw.svg",
    phone_code: "+250",
    country_code3: "RWA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 145,
    name: "Saint Kitts and Nevis",
    country_code: "KN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/kn.svg",
    phone_code: "+1-869",
    country_code3: "KNA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 146,
    name: "Saint Lucia",
    country_code: "LC",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lc.svg",
    phone_code: "+1-758",
    country_code3: "LCA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 147,
    name: "Saint Vincent and the Grenadines",
    country_code: "VC",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/vc.svg",
    phone_code: "+1-784",
    country_code3: "VCT",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 148,
    name: "Samoa",
    country_code: "WS",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ws.svg",
    phone_code: "+685",
    country_code3: "WSM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 149,
    name: "San Marino",
    country_code: "SM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sm.svg",
    phone_code: "+378",
    country_code3: "SMR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 150,
    name: "Sao Tome and Principe",
    country_code: "ST",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/st.svg",
    phone_code: "+239",
    country_code3: "STP",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 151,
    name: "Saudi Arabia",
    country_code: "SA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sa.svg",
    phone_code: "+966",
    country_code3: "SAU",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 152,
    name: "Senegal",
    country_code: "SN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sn.svg",
    phone_code: "+221",
    country_code3: "SEN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 153,
    name: "Serbia",
    country_code: "RS",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/rs.svg",
    phone_code: "+381",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 154,
    name: "Seychelles",
    country_code: "SC",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sc.svg",
    phone_code: "+248",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 155,
    name: "Sierra Leone",
    country_code: "SL",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sl.svg",
    phone_code: "+232",
    country_code3: "SLE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 156,
    name: "Singapore",
    country_code: "SG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sg.svg",
    phone_code: "+65",
    country_code3: "SGP",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 157,
    name: "Slovakia",
    country_code: "SK",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sk.svg",
    phone_code: "+421",
    country_code3: "SVK",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 158,
    name: "Slovenia",
    country_code: "SI",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/si.svg",
    phone_code: "+386",
    country_code3: "SVN",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 159,
    name: "Solomon Islands",
    country_code: "SB",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sb.svg",
    phone_code: "+677",
    country_code3: "SLB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 160,
    name: "Somalia",
    country_code: "SO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/so.svg",
    phone_code: "+252",
    country_code3: "SOM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 161,
    name: "South Africa",
    country_code: "ZA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/za.svg",
    phone_code: "+27",
    country_code3: "ZAF",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 162,
    name: "South Sudan",
    country_code: "SS",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ss.svg",
    phone_code: "+211",
    country_code3: "SSD",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 163,
    name: "Spain",
    country_code: "ES",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/es.svg",
    phone_code: "+34",
    country_code3: "ESP",
    continent_id: null,
    is_restricted: 0,
    continent: "Europe",
    iso_code: null,
  },
  {
    id: 164,
    name: "Sri Lanka",
    country_code: "LK",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/lk.svg",
    phone_code: "+94",
    country_code3: "LKA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 165,
    name: "Sudan",
    country_code: "SD",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sd.svg",
    phone_code: "+249",
    country_code3: "SDN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 166,
    name: "Suriname",
    country_code: "SR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sr.svg",
    phone_code: "+597",
    country_code3: "SUR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 167,
    name: "Swaziland",
    country_code: "SZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+268",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 168,
    name: "Sweden",
    country_code: "SE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/se.svg",
    phone_code: "+46",
    country_code3: "SWE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 169,
    name: "Switzerland",
    country_code: "CH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ch.svg",
    phone_code: "+41",
    country_code3: "CHE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 170,
    name: "Syria",
    country_code: "SY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/sy.svg",
    phone_code: "+963",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 171,
    name: "Taiwan",
    country_code: "TW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tw.svg",
    phone_code: "+886",
    country_code3: "TWN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 172,
    name: "Tajikistan",
    country_code: "TJ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tj.svg",
    phone_code: "+992",
    country_code3: "TJK",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 173,
    name: "Tanzania",
    country_code: "TZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tz.svg",
    phone_code: "+255",
    country_code3: "TZA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 174,
    name: "Thailand",
    country_code: "TH",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/th.svg",
    phone_code: "+66",
    country_code3: "THA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 175,
    name: "Togo",
    country_code: "TG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tg.svg",
    phone_code: "+228",
    country_code3: "TGO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 176,
    name: "Tonga",
    country_code: "TO",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/to.svg",
    phone_code: "+676",
    country_code3: "TON",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 177,
    name: "Trinidad and Tobago",
    country_code: "TT",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tt.svg",
    phone_code: "+1-868",
    country_code3: "TTO",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 178,
    name: "Tunisia",
    country_code: "TN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tn.svg",
    phone_code: "+216",
    country_code3: "TUN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 179,
    name: "Turkey",
    country_code: "TR",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tr.svg",
    phone_code: "+90",
    country_code3: "TUR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 180,
    name: "Turkmenistan",
    country_code: "TM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tm.svg",
    phone_code: "+993",
    country_code3: "TKM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 181,
    name: "Tuvalu",
    country_code: "TV",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/tv.svg",
    phone_code: "+688",
    country_code3: "TUV",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 182,
    name: "Uganda",
    country_code: "UG",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ug.svg",
    phone_code: "+256",
    country_code3: "UGA",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 183,
    name: "Ukraine",
    country_code: "UA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ua.svg",
    phone_code: "+380",
    country_code3: "UKR",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 184,
    name: "United Arab Emirates",
    country_code: "AE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ae.svg",
    phone_code: "+971",
    country_code3: "ARE",
    continent_id: 3,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 185,
    name: "United Kingdom",
    country_code: "GB",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/gb.svg",
    phone_code: "+44",
    country_code3: "GBR",
    continent_id: 4,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 186,
    name: "United States",
    country_code: "US",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/us.svg",
    phone_code: "+1",
    country_code3: "USA",
    continent_id: 5,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 187,
    name: "Uruguay",
    country_code: "UY",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/uy.svg",
    phone_code: "+598",
    country_code3: "URY",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 188,
    name: "Uzbekistan",
    country_code: "UZ",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/uz.svg",
    phone_code: "+998",
    country_code3: "UZB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 189,
    name: "Vanuatu",
    country_code: "VU",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/vu.svg",
    phone_code: "+678",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 190,
    name: "Vatican City",
    country_code: "VA",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/xx.svg",
    phone_code: "+379",
    country_code3: null,
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 191,
    name: "Venezuela",
    country_code: "VE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ve.svg",
    phone_code: "+58",
    country_code3: "VEN",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 192,
    name: "Vietnam",
    country_code: "VN",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/vn.svg",
    phone_code: "+84",
    country_code3: "VNM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 193,
    name: "Yemen",
    country_code: "YE",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/ye.svg",
    phone_code: "+967",
    country_code3: "YEM",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 194,
    name: "Zambia",
    country_code: "ZM",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/zm.svg",
    phone_code: "+260",
    country_code3: "ZMB",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
  {
    id: 195,
    name: "Zimbabwe",
    country_code: "ZW",
    flag_url: "https://flagicons.lipis.dev/flags/4x3/zw.svg",
    phone_code: "+263",
    country_code3: "ZWE",
    continent_id: null,
    is_restricted: 0,
    continent: null,
    iso_code: null,
  },
];

// Helper functions
export const getCountryById = (id) => {
  return countries.find((country) => country.id === id);
};

export const getCountryByCode = (code) => {
  return countries.find((country) => country.country_code === code);
};

export const getCountryByName = (name) => {
  return countries.find(
    (country) => country.name.toLowerCase() === name.toLowerCase()
  );
};

export const getCountriesByContinent = (continentId) => {
  return countries.filter((country) => country.continent_id === continentId);
};

export const getAllCountryCodes = () => {
  return countries.map((country) => country.country_code);
};

export const getAllPhoneCodes = () => {
  return countries.map((country) => ({
    name: country.name,
    code: country.phone_code,
    country_code: country.country_code,
  }));
};

// Simplified fetchCountries thunk - now just returns static data
export const fetchCountries = createAsyncThunk(
  "countries/fetchCountries",
  async (_, { rejectWithValue }) => {
    try {
      console.log("🌍 Using static countries data");
      console.log("📊 Countries data structure:", {
        total: countries.length,
        firstCountry: countries[0],
        keys: Object.keys(countries[0]),
        hasPhoneCode: countries[0].hasOwnProperty("phone_code"),
        hasPhoneCodeValue: countries[0].phone_code,
        sampleData: countries.slice(0, 3), // First 3 countries
      });
      return countries;
    } catch (error) {
      console.error("💥 Error loading countries:", error);
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for fetching a single country
export const fetchCountry = createAsyncThunk(
  "countries/fetchCountry",
  async (countryId, { rejectWithValue }) => {
    try {
      const country = getCountryById(countryId);
      if (!country) {
        throw new Error(`Country with ID ${countryId} not found`);
      }
      return country;
    } catch (error) {
      console.error("Failed to fetch country:", error);
      return rejectWithValue(error.message);
    }
  }
);

// Initialize with the static countries data
const initialState = {
  countries: countries, // Initialize with the static data
  selectedCountry: null,
  loading: false,
  error: null,
  lastUpdated: null,
};

const countriesSlice = createSlice({
  name: "countries",
  initialState,
  reducers: {
    setSelectedCountry: (state, action) => {
      state.selectedCountry = action.payload;
    },
    clearError: (state) => {
      state.error = null;
    },
    clearCountries: (state) => {
      state.countries = [];
    },
    updateCountry: (state, action) => {
      const { id, updates } = action.payload;
      const index = state.countries.findIndex((country) => country.id === id);
      if (index !== -1) {
        state.countries[index] = { ...state.countries[index], ...updates };
      }
    },
    addCountry: (state, action) => {
      state.countries.push(action.payload);
    },
    removeCountry: (state, action) => {
      state.countries = state.countries.filter(
        (country) => country.id !== action.payload
      );
    },
    refreshCountries: (state) => {
      // Reset to initial static data
      state.countries = countries;
    },
    resetCountriesState: () => initialState,
  },
  extraReducers: (builder) => {
    builder
      // Fetch countries
      .addCase(fetchCountries.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchCountries.fulfilled, (state, action) => {
        state.loading = false;
        state.countries = action.payload;
        state.error = null;
        state.lastUpdated = new Date().getTime();

        console.log("✅ Countries loaded into Redux:", {
          count: action.payload.length,
          stateCount: state.countries.length,
          sample: state.countries.slice(0, 2),
        });
      })
      .addCase(fetchCountries.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload || action.error.message;
        console.error("❌ Countries fetch rejected:", state.error);
      })
      // Fetch single country
      .addCase(fetchCountry.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchCountry.fulfilled, (state, action) => {
        state.loading = false;
        state.selectedCountry = action.payload;
        state.error = null;
      })
      .addCase(fetchCountry.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload;
      });
  },
});

export const {
  setSelectedCountry,
  clearError,
  clearCountries,
  updateCountry,
  addCountry,
  removeCountry,
  refreshCountries,
  resetCountriesState,
} = countriesSlice.actions;

// Selectors
export const selectCountries = (state) => state.countries.countries;
export const selectSelectedCountry = (state) => state.countries.selectedCountry;
export const selectCountriesLoading = (state) => state.countries.loading;
export const selectCountriesError = (state) => state.countries.error;
export const selectCountriesLastUpdated = (state) =>
  state.countries.lastUpdated;

// Additional useful selectors
export const selectCountryById = (state, countryId) =>
  state.countries.countries.find((country) => country.id === countryId);

export const selectCountriesByRegion = (state, region) =>
  state.countries.countries.filter((country) => country.region === region);

// Memoized selector for React Select options
export const selectCountriesOptions = createSelector(
  [(state) => state.countries?.countries || []],
  (countries) => {
    console.log("🔍 selectCountriesOptions - raw countries data:", {
      countriesCount: countries.length,
      isArray: Array.isArray(countries),
      firstItem: countries[0],
      allKeys: countries.length > 0 ? Object.keys(countries[0]) : "no data",
    });

    if (!countries || !Array.isArray(countries)) {
      console.warn("⚠️ No countries data available for options");
      return [];
    }

    const options = countries.map((country) => ({
      value: country.name,
      label: country.name,
      phoneCode: country.phone_code || country.phoneCode,
      country_code: country.country_code,
      id: country.id,
    }));

    console.log("🔄 Processed country options:", {
      optionsCount: options.length,
      firstOption: options[0],
      optionsStructure: options.slice(0, 3), // First 3 options
    });

    return options;
  }
);

// Safe version of the selector with error handling
export const selectCountriesOptionsSafe = (state) => {
  try {
    return selectCountriesOptions(state);
  } catch (error) {
    console.warn("Error in selectCountriesOptions, using fallback:", error);
    return [
      {
        value: 186,
        label: "United States",
        phoneCode: "+1",
        country_code: "US",
      },
      {
        value: 185,
        label: "United Kingdom",
        phoneCode: "+44",
        country_code: "GB",
      },
      { value: 32, label: "Canada", phoneCode: "+1", country_code: "CA" },
      { value: 9, label: "Australia", phoneCode: "+61", country_code: "AU" },
    ];
  }
};

// Selector for phone code options specifically
export const selectPhoneCodeOptions = createSelector(
  [selectCountries],
  (countries) => {
    return countries.map((country) => ({
      value: country.phone_code,
      label: `${country.phone_code} (${country.name})`,
      country: {
        id: country.id, // ✅ Explicitly pass the ID
        name: country.name, // ✅ Pass other needed properties
        flag_url: country.flag_url,
      },
      // Or as an alternative, you can add these at the top level:
      countryId: country.id, // ✅ Direct access to country ID
      countryName: country.name,
    }));
  }
);

export const selectCountryByCode = (state, phoneCode) =>
  state.countries.countries.find((country) => country.phone_code === phoneCode);

export const selectCountriesSorted = (state, sortBy = "name") =>
  [...state.countries.countries].sort((a, b) => {
    if (sortBy === "name") {
      return a.name.localeCompare(b.name);
    }
    if (sortBy === "phoneCode") {
      return a.phone_code.localeCompare(b.phone_code);
    }
    return 0;
  });

// Selector for countries that have phone codes
export const selectCountriesWithPhoneCodes = createSelector(
  [selectCountries],
  (countries) => countries.filter((country) => country.phone_code)
);

// Selector for popular countries (customizable)
export const selectPopularCountries = createSelector(
  [selectCountries],
  (countries) => {
    const popularCountryCodes = [
      "US",
      "GB",
      "CA",
      "AU",
      "DE",
      "FR",
      "IN",
      "CN",
      "JP",
    ];
    return countries.filter((country) =>
      popularCountryCodes.includes(country.country_code)
    );
  }
);

// Selector to find country by name or code
export const selectCountryBySearchTerm = (state, searchTerm) => {
  if (!searchTerm) return [];

  const term = searchTerm.toLowerCase();
  return state.countries.countries.filter(
    (country) =>
      (country.name && country.name.toLowerCase().includes(term)) ||
      (country.country_code &&
        country.country_code.toLowerCase().includes(term)) ||
      (country.phone_code && country.phone_code.includes(term))
  );
};

export default countriesSlice.reducer;
